---
title: "snATAC-seq demo"
author: "Giuditta"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## snATAC-seq demo dataset


In this notebook I will try Signac package guide to analyse a Human PBMC dataset, snATACseq data, 10x Genomics. 

First, dun this command to download required packages:

wget https://cf.10xgenomics.com/samples/cell-atac/1.0.1/atac_v1_pbmc_10k/atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5
wget https://cf.10xgenomics.com/samples/cell-atac/1.0.1/atac_v1_pbmc_10k/atac_v1_pbmc_10k_singlecell.csv
wget https://cf.10xgenomics.com/samples/cell-atac/1.0.1/atac_v1_pbmc_10k/atac_v1_pbmc_10k_fragments.tsv.gz
wget https://cf.10xgenomics.com/samples/cell-atac/1.0.1/atac_v1_pbmc_10k/atac_v1_pbmc_10k_fragments.tsv.gz.tbi



Initialize and match git repository:

git init
git remote add origin https://github.com/giuditta2024/snATAC-seq.git
git branch -m master main   # rename master to main 


```{r}
setwd("/group/soranzo/giuditta.clerici/snATAC_demo")
```


```{r}
if (!requireNamespace("EnsDb.Hsapiens.v75", quietly = TRUE))
    BiocManager::install("EnsDb.Hsapiens.v75")
```

